[programs.localnet]
gappe = "3qFjQjHysMD7vDkpC7DBAyUhNkMQEPYRVWzkokZHLQfg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/pepsighan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
